version: '3'
services:
  mongo:
    image: mongo:latest
    env_file: .env
    environment:
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
    ports:
      - "6000:27017"
    volumes:
      - mongo:/data/db
  web:
    container_name: api_backend
    build: .
    restart: always
    env_file: .env
    volumes:
      - .:/task_list_app
    depends_on:
      - mongo

volumes:
  mongo:
