version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      DB_URL: ${DB_URL}
      DB_NAME: ${DB_NAME}
    volumes:
      - mongo:/task_list_app/data/db

  web:
    build:
      context: .
    env_file: .env
    command: sh -c "python3 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8001:8000"
    volumes:
      - .:/task_list_app
    depends_on:
      - mongo


volumes:
  mongo: